import React from "react";
import LegalLayout from "../components/LegalLayout";

function TermsConditions() {
  return (
    <LegalLayout title="Terms & Conditions">

      <p>
        By using AceInterview.AI, you agree to the following terms and conditions.
      </p>

      <h2 className="text-xl font-semibold text-white">
        Platform Usage
      </h2>

      <ul className="list-disc ml-6 space-y-2">
        <li>Users must provide accurate information.</li>
        <li>Users must not misuse the platform.</li>
        <li>Users must not attempt to disrupt services.</li>
      </ul>

      <h2 className="text-xl font-semibold text-white">
        AI Generated Content
      </h2>

      <p>
        Interview questions, feedback, and reports are generated by AI
        and are intended for educational and preparation purposes only.
      </p>

      <h2 className="text-xl font-semibold text-white">
        Service Availability
      </h2>

      <p>
        We reserve the right to modify, suspend, or discontinue any feature
        without prior notice.
      </p>

      <h2 className="text-xl font-semibold text-white">
        Acceptance
      </h2>

      <p>
        Continued use of AceInterview.AI indicates acceptance of these terms.
      </p>

    </LegalLayout>
  );
}

export default TermsConditions;